# Generated by Django 5.0.9 on 2024-10-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('nearest_maintenance', models.DateField()),
                ('next_maintenance', models.DateField()),
            ],
        ),
    ]
