# Generated by Django 5.0.9 on 2024-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('delete_status', models.BooleanField(db_column='delete_status_', default=False)),
                ('day_delete', models.DateTimeField(blank=True, db_column='day_delete_', null=True)),
                ('id', models.CharField(db_column='id_', max_length=60, primary_key=True, serialize=False)),
                ('floor', models.IntegerField(db_column='flor_')),
                ('status', models.CharField(db_column='status_', max_length=60)),
                ('num_apartment', models.CharField(db_column='num_apartment_', max_length=255)),
                ('num_bedroom', models.IntegerField(db_column='num_bedroom_')),
                ('square', models.DecimalField(db_column='square_', decimal_places=2, max_digits=10)),
                ('rent_price', models.DecimalField(db_column='rent_price_', decimal_places=2, max_digits=10)),
                ('address', models.CharField(db_column='address_', max_length=255)),
            ],
            options={
                'db_table': 'apartment_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('delete_status', models.BooleanField(default=False)),
                ('day_delete', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('id_apartment', models.CharField(max_length=60)),
                ('id_user', models.CharField(max_length=60)),
                ('complaint_date', models.DateTimeField()),
                ('expected_completion_date', models.DateTimeField(blank=True, null=True)),
                ('content_of_complaint', models.TextField()),
                ('proof_img', models.TextField(blank=True, null=True)),
                ('id_staff', models.CharField(max_length=60)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'complaints_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('delete_status', models.BooleanField(db_column='delete_status_', default=False)),
                ('day_delete', models.DateTimeField(blank=True, db_column='day_delete_', null=True)),
                ('id', models.CharField(db_column='id_', max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=150)),
                ('warranty', models.DateTimeField(blank=True, db_column='warranty_', null=True)),
                ('date_purchase', models.DateTimeField(blank=True, db_column='date_purchase_', null=True)),
                ('maintenance_date', models.DateTimeField(blank=True, db_column='maintenance_date_', null=True)),
                ('location', models.TextField(blank=True, db_column='location_', null=True)),
                ('status', models.CharField(db_column='status_', max_length=60)),
            ],
            options={
                'db_table': 'equipment_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRepair',
            fields=[
                ('delete_status', models.BooleanField(db_column='delete_status_', default=False)),
                ('day_delete', models.DateTimeField(blank=True, db_column='day_delete_', null=True)),
                ('id', models.CharField(db_column='id_', max_length=60, primary_key=True, serialize=False)),
                ('id_user', models.CharField(db_column='id_user_', max_length=60)),
                ('id_apartment', models.CharField(db_column='id_apartment_', max_length=60)),
                ('expected_completion_date', models.DateTimeField(blank=True, db_column='expected_completion_date_', null=True)),
                ('repair_content', models.TextField(db_column='repair_content_')),
                ('condition_of_damage', models.TextField(db_column='condition_of_damage_')),
                ('id_equipment', models.CharField(db_column='id_equipment_', max_length=60)),
            ],
            options={
                'db_table': 'maintenance_repair_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('delete_status', models.BooleanField(default=False)),
                ('day_delete', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=60)),
                ('id_service', models.CharField(max_length=60)),
                ('id_income', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=60)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_dateline', models.DateTimeField()),
                ('id_type_payment', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'payment_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('delete_status', models.BooleanField(default=False)),
                ('day_delete', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('id_apartment', models.CharField(max_length=60)),
                ('tenant_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateTimeField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'rental_request_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleHomeInspection',
            fields=[
                ('delete_status', models.BooleanField(default=False)),
                ('day_delete', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('id_apartment', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'schedule_a_home_inspection_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('delete_status', models.BooleanField(db_column='delete_status_', default=False)),
                ('day_delete', models.DateTimeField(blank=True, db_column='day_delete_', null=True)),
                ('id', models.CharField(db_column='id_', max_length=60, primary_key=True, serialize=False)),
                ('id_role', models.CharField(db_column='id_role_', max_length=60)),
                ('name', models.CharField(db_column='name_', max_length=255)),
                ('phone', models.CharField(db_column='phone_', max_length=30)),
                ('gender', models.CharField(db_column='gender_', max_length=10)),
                ('start_day', models.DateTimeField(db_column='start_day_')),
                ('end_day', models.DateTimeField(blank=True, db_column='end_day_', null=True)),
                ('status', models.CharField(db_column='status_', max_length=60)),
                ('password', models.CharField(db_column='password_', max_length=255)),
                ('address', models.CharField(db_column='address_', max_length=255)),
            ],
            options={
                'db_table': 'staff_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('delete_status', models.BooleanField(db_column='delete_status_', default=False)),
                ('day_delete', models.DateTimeField(blank=True, db_column='day_delete_', null=True)),
                ('id', models.CharField(db_column='id_', max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255)),
                ('phone', models.CharField(db_column='phone_', max_length=30)),
                ('address', models.CharField(db_column='address_', max_length=255)),
            ],
            options={
                'db_table': 'suppliers_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalMaintenance',
            fields=[
                ('delete_status', models.BooleanField(db_column='delete_status_', default=False)),
                ('day_delete', models.DateTimeField(blank=True, db_column='day_delete_', null=True)),
                ('id', models.CharField(db_column='id_', max_length=60, primary_key=True, serialize=False)),
                ('id_staff_send', models.CharField(db_column='id_staff_send_', max_length=60)),
                ('id_staff_action', models.CharField(db_column='id_staff_action_', max_length=60)),
                ('status', models.CharField(db_column='status_', max_length=255)),
                ('name', models.CharField(db_column='name_', max_length=255)),
                ('nearest_maintenance', models.DateTimeField(blank=True, db_column='nearest_maintenance_', null=True)),
                ('next_maintenance', models.DateTimeField(blank=True, db_column='next_maintenance_', null=True)),
                ('location', models.CharField(db_column='location_', max_length=255)),
                ('maintenance_task', models.CharField(db_column='maintenance_task_', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description_', null=True)),
                ('floor', models.IntegerField(db_column='floor_')),
            ],
            options={
                'db_table': 'technical_maintenance_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TechnicalRepair',
            fields=[
                ('delete_status', models.BooleanField(db_column='delete_status_', default=False)),
                ('day_delete', models.DateTimeField(blank=True, db_column='day_delete_', null=True)),
                ('id', models.CharField(db_column='id_', max_length=60, primary_key=True, serialize=False)),
                ('id_staff_send', models.CharField(db_column='id_staff_send_', max_length=60)),
                ('id_staff_action', models.CharField(db_column='id_staff_action_', max_length=60)),
                ('status', models.CharField(db_column='status_', max_length=255)),
                ('name', models.CharField(db_column='name_', max_length=255)),
                ('nearest_repair', models.DateTimeField(blank=True, db_column='nearest_repair_', null=True)),
                ('next_repair', models.DateTimeField(blank=True, db_column='next_repair_', null=True)),
                ('location', models.CharField(db_column='location_', max_length=255)),
                ('repair_task', models.CharField(db_column='repair_task_', max_length=255)),
                ('description', models.TextField(blank=True, db_column='description_', null=True)),
                ('floor', models.IntegerField(db_column='floor_')),
                ('id_equipment', models.CharField(db_column='id_equipment_', max_length=60)),
            ],
            options={
                'db_table': 'technical_repair_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeEquipment',
            fields=[
                ('delete_status', models.BooleanField(db_column='delete_status_', default=False)),
                ('day_delete', models.DateTimeField(blank=True, db_column='day_delete_', null=True)),
                ('id', models.CharField(db_column='id_', max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255)),
            ],
            options={
                'db_table': 'type_equipment_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('delete_status', models.BooleanField(db_column='delete_status_', default=False)),
                ('day_delete', models.DateTimeField(blank=True, db_column='day_delete_', null=True)),
                ('id', models.CharField(db_column='id_', max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_', max_length=255)),
                ('email', models.EmailField(db_column='email_', max_length=255)),
                ('phone', models.CharField(db_column='phone_', max_length=30)),
                ('gender', models.CharField(db_column='gender_', max_length=10)),
                ('ssn', models.CharField(db_column='ssn_', max_length=9)),
                ('status', models.CharField(db_column='status_', max_length=60)),
                ('password', models.CharField(db_column='password_', max_length=255)),
                ('debt', models.DecimalField(db_column='debt_', decimal_places=2, max_digits=10)),
                ('total_payment', models.DecimalField(db_column='total_payment_', decimal_places=2, max_digits=10)),
                ('start_day', models.DateTimeField(db_column='start_day_')),
                ('end_day', models.DateTimeField(blank=True, db_column='end_day_', null=True)),
                ('address', models.CharField(db_column='address_', max_length=255)),
            ],
            options={
                'db_table': 'user_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, default=200000.0, max_digits=5)),
                ('build_year', models.IntegerField(default=2020)),
                ('num_apartments', models.IntegerField(default=90)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('delete_status', models.BooleanField(db_column='delete_status_', default=False)),
                ('day_delete', models.DateTimeField(blank=True, db_column='day_delete_', null=True)),
                ('id', models.CharField(db_column='id_', max_length=60, primary_key=True, serialize=False)),
                ('name_role', models.CharField(db_column='name_role_', max_length=255)),
            ],
        ),
    ]
